OPENAI_API_KEY = "sk-..."
HUGGINGFACE_TOKEN = "hf_..."

IDENTIFY_SPEAKER = False
DEVICE = "cuda"
BATCH_SIZE = 16
COMPUTE_TYPE = "float16"
LANG_DIC = {
    "zh": "Chinese",
    "en": "English",
    "es": "Spanish",
    "fr": "French",
    "de": "German",
    "ja": "Japanese",
}
SUBTITLE_STYLE = "仓耳今楷"
SUBTITLE_FONT = "仓耳今楷03 W04"
SUBTITLE_FONT_SIZE = 18
SUBTITLE_FONT_COLOR = "&H00F7C34F"  # #4fc3f7
SUBTITLE_FONT_SHADOW_COLOR = "&H000000FF"
SUBTITLE_FONT_SHADOW_X = 0
SUBTITLE_FONT_SHADOW_Y = 0
SUBTITLE_FONT_SHADOW_BLUR = 0
SUBTITLE_FONT_SHADOW_OPACITY = 0.9
SUBTITLE_FONT_SHADOW_STYLE = 1
SUBTITLE_FONT_SHADOW_ALPHA = 2
SUBTITLE_FONT_SHADOW_SPACING = 8
SUBTITLE_FONT_SHADOW_ANGLE = 8
SUBTITLE_FONT_SHADOW_USE_BORDER = 10
SUBTITLE_FONT_SHADOW_BORDER = 1
ASS_STYLE = "仓耳今楷,仓耳今楷03 W04,18,&H00F7C34F,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,0.9,1,2,8,8,10,1"
target_language = "zh"
